quarkus:
  http:
    root-path: "/api"
    non-application-root-path: ${quarkus.http.root-path}
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5p [%-50.50c{2.}] - %s%e%n"
    level: "INFO"
    category:
      "eu.ill":
        level: ${RTSP_TO_FMP4_LOGGING_LEVEL:DEBUG}

server:
  worker:
    intialisation-timout-ms: ${RTSP_TO_FMP4_INITIALISATION_TIMEOUT_MS:30000}
    ffmpeg-path: ${RTSP_TO_FMP4_FFMPEG_PATH:/opt/homebrew/bin/ffmpeg}
  publisher:
    port: ${RTSP_TO_FMP4_PUBLISHER_PORT:8084}

